/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.EduPoLy.UI;

import com.EduPoLy.DAO.ChuyenDeDAO;
import com.EduPoLy.Entity.ChuyenDe;
import com.EduPoLy.Entity.NhanVien;
import com.EduPoLy.utils.AUTH;
import com.EduPoLy.utils.MsgBOX;
import com.EduPoLy.utils.Ximage;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author DUY PHUONG
 */
public class QuanlyCDJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanlyJDialog
     */
    public QuanlyCDJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblhinh = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmacd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttencd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtthoiluong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txthocphi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmota = new javax.swing.JTextArea();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthemmoi = new javax.swing.JButton();
        btnfirst = new javax.swing.JButton();
        btnprev = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblquanlyCD = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("LOGO");

        lblhinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));
        lblhinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhinhMouseClicked(evt);
            }
        });

        jLabel4.setText("Mã Tên Chuyên Đề");

        jLabel5.setText("Tên Chuyên Đề");

        jLabel6.setText("Thời Lượng(Giờ)");

        jLabel7.setText("Học Phí");

        jLabel8.setText("Mô Tả Chuyên Đề");

        txtmota.setColumns(20);
        txtmota.setRows(5);
        jScrollPane1.setViewportView(txtmota);

        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/save-icon.png"))); // NOI18N
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/update-icon.png"))); // NOI18N
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Close-icon.png"))); // NOI18N
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthemmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-New-icon.png"))); // NOI18N
        btnthemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemmoiActionPerformed(evt);
            }
        });

        btnfirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-First-icon.png"))); // NOI18N
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        btnprev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Rewind-icon.png"))); // NOI18N
        btnprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprevActionPerformed(evt);
            }
        });

        btnnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Forward-icon.png"))); // NOI18N
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Last-icon.png"))); // NOI18N
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnthemmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnfirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnprev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnlast))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblhinh, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthocphi)
                            .addComponent(txtthoiluong)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txttencd)
                            .addComponent(txtmacd)))
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtmacd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttencd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtthoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthocphi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblhinh, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsua)
                            .addComponent(btnthem)
                            .addComponent(btnxoa)
                            .addComponent(btnthemmoi)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnfirst, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnprev, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnlast, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnnext, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("CẬP NHẬT", jPanel1);

        tblquanlyCD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MACD  ", "TENCD   ", "HOC PHI", "THOI LUONG ", "HINH      ", "MoTa   "
            }
        ));
        tblquanlyCD.setRowHeight(22);
        tblquanlyCD.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblquanlyCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblquanlyCDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblquanlyCDMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblquanlyCD);

        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        tabs.addTab("DANH SÁCH ", jPanel2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("QUẢN LÝ CHUYÊN ĐỀ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblhinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhinhMouseClicked
        // TODO add your handling code here:
        this.chonAnh();
    }//GEN-LAST:event_lblhinhMouseClicked

    private void tblquanlyCDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblquanlyCDMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblquanlyCD.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblquanlyCDMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (isValidate()) {
            this.insert();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnthemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemmoiActionPerformed
        // TODO add your handling code here:
        this.reset();
    }//GEN-LAST:event_btnthemmoiActionPerformed

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
        // TODO add your handling code here:
        this.fisrt();
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnprevActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnlastActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.print();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblquanlyCDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblquanlyCDMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblquanlyCDMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanlyCDJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanlyCDJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanlyCDJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanlyCDJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanlyCDJDialog dialog = new QuanlyCDJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprev;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemmoi;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblhinh;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblquanlyCD;
    private javax.swing.JTextField txthocphi;
    private javax.swing.JTextField txtmacd;
    private javax.swing.JTextArea txtmota;
    private javax.swing.JTextField txttencd;
    private javax.swing.JTextField txtthoiluong;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        setTitle("QUẢN LÝ CHUYÊN ĐỀ");
        this.filltable();
        this.updatestatus();
        this.row = -1;
    }
    ChuyenDeDAO cddao = new ChuyenDeDAO();
    int row = -1;
    DefaultTableModel model;

    void filltable() {
        model = (DefaultTableModel) tblquanlyCD.getModel();//mo hinh du lieu cua bang
        model.setRowCount(0);
        try {
            List<ChuyenDe> list = cddao.selectAll();//Doc du lieu tu csdl
            for (ChuyenDe cd : list) {
                model.addRow(new Object[]{cd.getMaCD(), cd.getTenCD(), cd.getHocPhi(), cd.getThoiLuong(),
                    cd.getHinh(), cd.getMoTa()});
            }
        } catch (Exception e) {
            MsgBOX.alert(this, "LOI TRUY VAN DU LIEU!!!");
        }
    }

    boolean isValidate() {
        if (txtmacd.getText().length() == 0) {
            MsgBOX.alert(this, "MA CHUYEN DE KHONG DUOC TRONG!!!");
            txtmacd.requestFocus();
            return false;
        }
        try {
            String manv = txtmacd.getText();
            if (cddao.selectByID(manv) != null) {
                throw new Exception();
            }
        } catch (Exception e) {
            MsgBOX.alert(this, "MA DA TON TAI!!!");
            txtmacd.requestFocus();
            txtmacd.setText("");
            return false;
        }
        if (txtmacd.getText().length() > 5) {
            MsgBOX.alert(this, "MA KHONG DUOC QUA 5 KY TU!!!");
            txtmacd.requestFocus();
            txtmacd.setText("");
            return false;
        }
        if (txttencd.getText().length() == 0) {
            MsgBOX.alert(this, "TEN CHUYEN DE KHONG DUOC TRONG!!!");
            txttencd.requestFocus();
            return false;
        }
        if (txtthoiluong.getText().length() == 0) {
            MsgBOX.alert(this, "THOI LUONG KHONG DUOC TRONG!!!");
            txtthoiluong.requestFocus();
            return false;
        }
        try {
            Integer.parseInt(txtthoiluong.getText());
        } catch (Exception e) {
            MsgBOX.alert(this, "THOI LUONG PHAI LA SO NGUYEN!!!");
            txtthoiluong.setText("");
            txtthoiluong.requestFocus();
            return false;
        }
        if (txthocphi.getText().length() == 0) {
            MsgBOX.alert(this, "HOC PHI KHONG DUOC TRONG!!!");
            txthocphi.requestFocus();
            return false;
        }
        try {
            Double.parseDouble(txthocphi.getText());
        } catch (Exception e) {
            MsgBOX.alert(this, "HOC PHI PHAI LA SO THUC!!!");
            txthocphi.setText("");
            txthocphi.requestFocus();
            return false;
        }
        if (txtmota.getText().length() == 0) {
            MsgBOX.alert(this, "NHAP MO TA!!!");
            txtmota.requestFocus();
            return false;
        }if (lblhinh.getIcon() == null) {
            MsgBOX.alert(this, "CHON ANH!!!");
            return false;
        }
        
        return true;
    }

    void setform(ChuyenDe cd) {
        txtmacd.setText(cd.getMaCD());
        txttencd.setText(cd.getTenCD());
        txthocphi.setText(String.valueOf(cd.getHocPhi()));
        txtthoiluong.setText(String.valueOf(cd.getThoiLuong()));
        if (cd.getHinh() != null) {
            lblhinh.setToolTipText(cd.getHinh());
            lblhinh.setIcon(Ximage.read(cd.getHinh()));
        }
        txtmota.setText(cd.getMoTa());
    }

    ChuyenDe getform() {
        ChuyenDe cd = new ChuyenDe();
        cd.setMaCD(txtmacd.getText());
        cd.setTenCD(txttencd.getText());
        cd.setHocPhi(Double.valueOf(txthocphi.getText()));
        cd.setThoiLuong(Integer.valueOf(txtthoiluong.getText()));
        cd.setHinh(lblhinh.getToolTipText());//lay ten thi hinh tu tooltip cua lable chua hinh
        cd.setMoTa(txtmota.getText());
        return cd;
    }

    void reset() {
        ChuyenDe cd = new ChuyenDe();
        this.setform(cd);
        lblhinh.setIcon(null);
        txtthoiluong.setText("");
        txthocphi.setText("");
        this.row = -1;
        this.updatestatus();
    }

    void insert() {
        ChuyenDe cd = getform();
        try {
            cddao.insert(cd);
            this.filltable();
            this.reset();
            MsgBOX.alert(this, "THEM MOI THANH CONG!!!");
        } catch (Exception e) {
            MsgBOX.alert(this, "THEM MOI THAT BAI!!!");
        }
    }

    void update() {
        ChuyenDe cd = getform();
        try {
            cddao.update(cd);
            this.filltable();
            MsgBOX.alert(this, "SUA THANH CONG!!!");
        } catch (Exception e) {
            MsgBOX.alert(this, "SUA THAT BAI!!!");
        }
    }

    void delete() {
        if (!AUTH.isManager()) {
            MsgBOX.alert(this, "BAN KHONG CO QUYEN XOA!!!");
        } else if (MsgBOX.confirm(this, "BAN CO THUC SU MUON XOA CHUYEN DE NAY?")) {
            try {
                String macd = txtmacd.getText();
                cddao.delete(macd);
                this.filltable();
                this.reset();
                MsgBOX.alert(this, "XOA THANH CONG!!!");
            } catch (Exception e) {
                MsgBOX.alert(this, "XOA THAT BAI!!!");
            }
        }
    }

    void edit() {
        String macd = (String) tblquanlyCD.getValueAt(this.row, 0);
        ChuyenDe cd = cddao.selectByID(macd);
        this.setform(cd);
        tabs.setSelectedIndex(0);
        this.updatestatus();
    }

    void fisrt() {
        this.row = 0;
        this.edit();
    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void next() {
        if (this.row < tblquanlyCD.getRowCount() - 1) {
            this.row++;
            this.edit();

        }
    }

    void last() {
        this.row = tblquanlyCD.getRowCount() - 1;
        this.edit();
    }

    void updatestatus() {
        boolean edit = (this.row >= 0);
        boolean fisrt = (this.row == 0);
        boolean last = (this.row == tblquanlyCD.getRowCount() - 1);
        //trang thai form
        txtmacd.setEditable(!edit);//khong duoc cap nhap ma.Khi nao gia tri edit=false thi moi dc cap nhap va nguoc lai
        btnthem.setEnabled(!edit);//khi hien thong tin tren o nhap thi khong hien button va nguoc lai
        btnxoa.setEnabled(edit);//khi co thong tin (true) thi hien buuton va nguoc lai
        btnsua.setEnabled(edit);//nhu tren
        //cac thanh dieu huong
        //khi trong trang thai edit thi moi hien button va nguoc lai
        btnfirst.setEnabled(edit && !fisrt);//chi hien len khi dang edit va khong phai la hang dau tien
        btnprev.setEnabled(edit && !fisrt);//nhu tren
        btnnext.setEnabled(edit && !last);//chi hien len khi dang edit va khong phai la hang cuoi cung
        btnlast.setEnabled(edit && !last);//nhu tren
    }

    void chonAnh() {
        JFileChooser filechoose = new JFileChooser();
        if (filechoose.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = filechoose.getSelectedFile();
            Ximage.save(file);//luu hinh anh vao thu muc logos
            ImageIcon icon = Ximage.read(file.getName());//doc hinh tu logos
            lblhinh.setIcon(icon);
            lblhinh.setToolTipText(file.getName());//giu ten hinh trong tooltip
        }
    }

    void print() {
        FileOutputStream excelfou = null;
        BufferedOutputStream excelBOU = null;
        XSSFWorkbook exceljtableExporter = null;
        //chon noi luu file 
        JFileChooser excelfile = new JFileChooser("d:\\prinexcel");
        //Thanh tiu de
        excelfile.setDialogTitle("Save As");
        //cac dang ten duoi mo rong cua excel
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlxs", "xlsm");
        excelfile.setFileFilter(fnef);
        int excelchoose = excelfile.showSaveDialog(null);

        //kiểm tra xem nút lưu có được nhấp không
        if (excelchoose == JFileChooser.APPROVE_OPTION) {
            try {
                //import thu vien apache poi excel
                exceljtableExporter = new XSSFWorkbook();
                XSSFSheet excelsheet = exceljtableExporter.createSheet("JTable Sheet");
                // vòng lặp để lấy cột và hàng của bảng
                for (int i = 0; i < model.getRowCount(); i++) {
                    XSSFRow excelrow = excelsheet.createRow(i);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        XSSFCell excelCell = excelrow.createCell(j);
                        excelCell.setCellValue(tblquanlyCD.getValueAt(i, j).toString());
                    }
                }
                //nối phần mở rộng tệp xlsx vào các tệp đã chọn. để tạo tên tệp duy nhất  
                excelfou = new FileOutputStream(excelfile.getSelectedFile() + ".xlsx");
                excelBOU = new BufferedOutputStream(excelfou);
                exceljtableExporter.write(excelBOU);
                JOptionPane.showMessageDialog(this, "TAO VA THEM FILE EXCEL THANH CONG!!!");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                Logger.getLogger(QuanLyNVQTJDialog.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    if (excelBOU != null) {
                        excelBOU.close();
                    }
                    if (excelfou != null) {
                        excelfou.close();
                    }
                    if (exceljtableExporter != null) {
                        exceljtableExporter.close();
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }

        }
    }
}
