/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.EduPoLy.UI;

import com.EduPoLy.DAO.ChuyenDeDAO;
import com.EduPoLy.DAO.KhoaHocDAO;
import com.EduPoLy.Entity.ChuyenDe;
import com.EduPoLy.Entity.KhoaHoc;
import com.EduPoLy.Entity.NguoiHoc;
import com.EduPoLy.utils.AUTH;
import com.EduPoLy.utils.MsgBOX;
import com.EduPoLy.utils.XDATE;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUY PHUONG
 */
public class QuanLyKHJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyKHJDialog
     */
    public QuanLyKHJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txthocphi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtthoiluong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnguoitao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtngaytao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtghichu = new javax.swing.JTextArea();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthemmoi = new javax.swing.JButton();
        btnfisrt = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        lbltencd = new javax.swing.JLabel();
        txtngaykg = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblqlkhoahoc = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cbochuyende = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Chuyên Đề");

        jLabel2.setText("Khai Giảng");

        jLabel3.setText("Học Phí");

        jLabel4.setText("Thời Lượng");

        jLabel5.setText("Người Tạo");

        jLabel6.setText("Ngày Tạo");

        jLabel7.setText("Ghi Chú");

        txtghichu.setColumns(20);
        txtghichu.setRows(5);
        jScrollPane2.setViewportView(txtghichu);

        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/save-icon.png"))); // NOI18N
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/update-icon.png"))); // NOI18N
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Close-icon.png"))); // NOI18N
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthemmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-New-icon.png"))); // NOI18N
        btnthemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemmoiActionPerformed(evt);
            }
        });

        btnfisrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-First-icon.png"))); // NOI18N
        btnfisrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfisrtActionPerformed(evt);
            }
        });

        btnprevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Rewind-icon.png"))); // NOI18N
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        btnnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Forward-icon.png"))); // NOI18N
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Last-icon.png"))); // NOI18N
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        lbltencd.setBackground(new java.awt.Color(204, 204, 204));
        lbltencd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltencd.setForeground(new java.awt.Color(51, 51, 255));
        lbltencd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txthocphi, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(txtnguoitao, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(lbltencd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtthoiluong)
                            .addComponent(txtngaytao, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(txtngaykg)))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addGap(18, 18, 18)
                        .addComponent(btnsua)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnthemmoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(btnfisrt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnprevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnnext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnlast)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltencd, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtngaykg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txthocphi, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtthoiluong))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnguoitao, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtngaytao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsua)
                    .addComponent(btnfisrt)
                    .addComponent(btnprevious)
                    .addComponent(btnnext)
                    .addComponent(btnlast)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btnthemmoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("CẬP NHẬT", jPanel2);

        tblqlkhoahoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MAKH ", "HOC PHI   ", "THOI LUONG", "KHAI GIANG ", "TAO BOI ", "NGAY TAO            "
            }
        ));
        tblqlkhoahoc.setRowHeight(22);
        tblqlkhoahoc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblqlkhoahoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblqlkhoahocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblqlkhoahoc);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        tabs.addTab("DANH SÁCH", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHUYÊN ĐỀ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 51, 51))); // NOI18N

        cbochuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbochuyendeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbochuyende, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cbochuyende, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabs))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (isValidate()) {
            this.insert();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnthemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemmoiActionPerformed
        // TODO add your handling code here:
        this.reset();
    }//GEN-LAST:event_btnthemmoiActionPerformed

    private void btnfisrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfisrtActionPerformed
        // TODO add your handling code here:
        this.fisrt();
    }//GEN-LAST:event_btnfisrtActionPerformed

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnlastActionPerformed

    private void tblqlkhoahocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblqlkhoahocMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblqlkhoahoc.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblqlkhoahocMouseClicked

    private void cbochuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbochuyendeActionPerformed
        // TODO add your handling code here:
        this.chonchuyende();
    }//GEN-LAST:event_cbochuyendeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKHJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKHJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKHJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKHJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyKHJDialog dialog = new QuanLyKHJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfisrt;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemmoi;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbochuyende;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltencd;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblqlkhoahoc;
    private javax.swing.JTextArea txtghichu;
    private javax.swing.JTextField txthocphi;
    private javax.swing.JTextField txtngaykg;
    private javax.swing.JTextField txtngaytao;
    private javax.swing.JTextField txtnguoitao;
    private javax.swing.JTextField txtthoiluong;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        setTitle("QUẢN LÝ KHÓA HỌC");
        this.fillcomboboxchuyende();

    }
    KhoaHocDAO khdao = new KhoaHocDAO();
    ChuyenDeDAO cddao = new ChuyenDeDAO();
    int row = -1;
    DefaultTableModel model;

    //Khi chọn 1 chuyên đề trên CBB thì đỗ dữ liêu vào bảng 
    void filltable() {
        model = (DefaultTableModel) tblqlkhoahoc.getModel();
        model.setRowCount(0);
        try {
            //lấy chuyên đề đc chọn
            ChuyenDe chuyende = (ChuyenDe) cbochuyende.getSelectedItem();
            //lấy ra danh sách khoahoc phụ thuộc vào chuyên đề đc chọn
            List<KhoaHoc> list = khdao.selectbyChuyende(chuyende.getMaCD());
            for (KhoaHoc kh : list) {
                model.addRow(new Object[]{kh.getMaKH(), kh.getHocPhi(), kh.getThoiLuong(), XDATE.toString(kh.getNgayKG(), "dd/MM/yyyy"),
                    kh.getMaNV(), XDATE.toString(kh.getNgayTao(), "dd/MM/yyyy")});
            }
        } catch (Exception e) {
            MsgBOX.alert(this, "Loi truy van du lieu!!!");
        }
    }

    //Lấy đối tượng model CBB ,quét sạch dữ liệu sau đó đổ tất cả các chuyển đề lên CBB
    //Hàm này phải đc gọi vào hàm init;
    void fillcomboboxchuyende() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbochuyende.getModel();
        model.removeAllElements();
        List<ChuyenDe> list = cddao.selectAll();
        for (ChuyenDe cd : list) {
            model.addElement(cd);
        }
    }

    void chonchuyende() {
        //lấy chuyên đề được chọn trong CBB
        ChuyenDe chuyende = (ChuyenDe) cbochuyende.getSelectedItem();
        //Hiển thị 1 số dữ liệu mặc định của khóa học lên form
        txtthoiluong.setText(String.valueOf(chuyende.getThoiLuong()));
        txthocphi.setText(String.valueOf(chuyende.getHocPhi()));
        lbltencd.setText(chuyende.getTenCD());
        txtghichu.setText(chuyende.getTenCD());

        //Đỗ lại dữ liệu khóa học lên bảng khi chuyên đề thay đổi
        this.filltable();
        this.row = -1;
        this.updatestatus();
        tabs.setSelectedIndex(1);
    }

    boolean isValidate() {
        if (txtngaykg.getText().length() == 0) {
            MsgBOX.alert(this, "BAN CHUA NHAP NGAY!!!");
            txtngaykg.requestFocus();
            return false;
        }
        try {
            XDATE.toDate(txtngaykg.getText(), "dd/MM/yyyy");
        } catch (Exception e) {
            MsgBOX.alert(this, "NGAY KHONG DUNG DINH DANG(dd/MM/yyyy)");
            txtngaykg.requestFocus();
            txtngaykg.setText("");
            return false;
        }
        if (txthocphi.getText().length() == 0) {
            MsgBOX.alert(this, "BAN CHUA NHAP HOC PHI!!!");
            txthocphi.requestFocus();
            return false;
        }
        try {
            Double HP = Double.parseDouble(txthocphi.getText());
            if (HP <= 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            MsgBOX.alert(this, "HOC PHI PHAI LA SO THUC VA PHAI >0!!!");
            txthocphi.setText("");
            txthocphi.requestFocus();
            return false;
        }
        if (txtthoiluong.getText().length() == 0) {
            MsgBOX.alert(this, "BAN CHUA NHAP THOI LUONG!!!");
            txtthoiluong.requestFocus();
            return false;
        }
        try {
            Integer TL = Integer.parseInt(txtthoiluong.getText());
            if (TL <= 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            MsgBOX.alert(this, "THOI LUONG PHAI LA SO NGUYEN VA PHAI >0!!!");
            txtthoiluong.setText("");
            txtthoiluong.requestFocus();
            return false;
        }
        if (txtghichu.getText().length() == 0) {
            MsgBOX.alert(this, "NHAP GHI CHU!!!");
            txtghichu.requestFocus();
            return false;
        }
        return true;
    }

    void insert() {
        KhoaHoc kh = getform();
        try {
            khdao.insert(kh);
            this.filltable();
            this.reset();
            MsgBOX.alert(this, "THEM THANH CONG!!!");
        } catch (Exception e) {
            MsgBOX.alert(this, "THEM THAT BAI!!!");
        }
    }

    void update() {
        KhoaHoc kh = getform();
        try {
            khdao.update(kh);
            this.filltable();
            this.reset();
            MsgBOX.alert(this, "SUA THANH CONG!!!");
        } catch (Exception e) {
            MsgBOX.alert(this, "SUA THAT BAI!!!");
        }
    }

    void delete() {
        if (!AUTH.isManager()) {
            MsgBOX.alert(this, "BAN KHONG CO QUYEN XOA!!!");
        } else if (MsgBOX.confirm(this, "BAN CO THUC SU MUON XOA MA NGUOI HOC NAY KHONG?")) {
            Integer manh = Integer.valueOf(cbochuyende.getToolTipText());
            try {
                khdao.delete(manh);
                this.filltable();
                this.reset();
                MsgBOX.alert(this, "XOA THANH CONG!!!");
            } catch (Exception e) {
                MsgBOX.alert(this, "XOA THAT BAI!!!");
            }
        }
    }

    void reset() {
        KhoaHoc kh = new KhoaHoc();
        ChuyenDe chuyende = (ChuyenDe) cbochuyende.getSelectedItem();//lay chuyen de dc chon o combobox
        kh.setMaNV(AUTH.user.getMaNV());
        kh.setMaCD(chuyende.getMaCD());
        kh.setNgayTao(XDATE.now());
        this.setform(kh);
        this.row = -1;
        this.updatestatus();
    }

    void edit() {
        Integer makh = (Integer) tblqlkhoahoc.getValueAt(this.row, 0);
        KhoaHoc kh = khdao.selectByID(makh);
        this.setform(kh);
        tabs.setSelectedIndex(0);
        this.updatestatus();
    }

    void setform(KhoaHoc kh) {
        //luu makh vao tam settooltiptext vi khong co cho tren form  
        //makh la identity
//        cbochuyende.setToolTipText(String.valueOf(kh.getMaKH()));
        cbochuyende.setSelectedItem(cddao.selectByID(kh.getMaCD()));
        txtngaykg.setText(XDATE.toString(kh.getNgayKG(), "dd/MM/yyyy"));
        txthocphi.setText(String.valueOf(kh.getHocPhi()));
        txtthoiluong.setText(String.valueOf(kh.getThoiLuong()));
        txtnguoitao.setText(kh.getMaNV());
        txtngaytao.setText(XDATE.toString(kh.getNgayTao(), "dd/MM/yyyy"));
        txtghichu.setText(kh.getGhiChu());
    }

    KhoaHoc getform() {
        KhoaHoc kh = new KhoaHoc();
        ChuyenDe chuyenDe = (ChuyenDe) cbochuyende.getSelectedItem();
//        kh.setMaKH(Integer.valueOf(cbochuyende.getToolTipText())); 
        kh.setMaCD(chuyenDe.getMaCD());
        kh.setHocPhi(Double.valueOf(txthocphi.getText()));
        kh.setThoiLuong(Integer.valueOf(txtthoiluong.getText()));
        kh.setNgayKG(XDATE.toDate(txtngaykg.getText(), "dd/MM/yyyy"));
        kh.setGhiChu(txtghichu.getText());
        kh.setMaNV(AUTH.user.getMaNV());
        kh.setNgayTao(XDATE.now());

        return kh;
    }

    void fisrt() {
        this.row = 0;
        this.edit();
    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void next() {
        if (this.row < tblqlkhoahoc.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    void last() {
        this.row = tblqlkhoahoc.getRowCount() - 1;
        this.edit();
    }

    void updatestatus() {
        boolean edit = (this.row >= 0);
        boolean fisrt = (this.row == 0);
        boolean last = (this.row == tblqlkhoahoc.getRowCount() - 1);
        //trang thai form
        lbltencd.setEnabled(!edit);//khong duoc cap nhap ma.Khi nao gia tri edit=false thi moi dc cap nhap va nguoc lai

        btnthem.setEnabled(!edit);//khi hien thong tin tren o nhap thi khong hien button va nguoc lai
        btnxoa.setEnabled(edit);//khi co thong tin (true) thi hien buuton va nguoc lai
        btnsua.setEnabled(edit);//nhu tren
        //cac thanh dieu huong
        //khi trong trang thai edit thi moi hien button va nguoc lai
        btnfisrt.setEnabled(edit && !fisrt);//chi hien len khi dang edit va khong phai la hang dau tien
        btnprevious.setEnabled(edit && !fisrt);//nhu tren
        btnnext.setEnabled(edit && !last);//chi hien len khi dang edit va khong phai la hang cuoi cung
        btnlast.setEnabled(edit && !last);//nhu tren
    }

}
