/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.EduPoLy.UI;

import com.EduPoLy.DAO.NhanVienDAO;
import com.EduPoLy.Entity.NhanVien;
import com.EduPoLy.utils.AUTH;
import com.EduPoLy.utils.MsgBOX;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author DUY PHUONG
 */
public class QuanLyNVQTJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyNVQTJDialog
     */
    public QuanLyNVQTJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdovaitro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        txtmatkhau = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtxacnhanmk = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdotruongphong = new javax.swing.JRadioButton();
        rdonhanvien = new javax.swing.JRadioButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthemmoi = new javax.swing.JButton();
        btnfisrt = new javax.swing.JButton();
        btnprev = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldanhsachnhanvien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("QUẢN LÝ NHÂN VỈÊN QUẢN TRỊ");

        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Mật Khẩu");

        jLabel4.setText("Xác Nhận Mật Khẩu");

        jLabel5.setText("Họ Và Tên");

        jLabel6.setText("Vai Trò");

        rdovaitro.add(rdotruongphong);
        rdotruongphong.setText("Trưởng Phòng");

        rdovaitro.add(rdonhanvien);
        rdonhanvien.setSelected(true);
        rdonhanvien.setText("Nhân Viên");

        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/save-icon.png"))); // NOI18N
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/update-icon.png"))); // NOI18N
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Close-icon.png"))); // NOI18N
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthemmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-New-icon.png"))); // NOI18N
        btnthemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemmoiActionPerformed(evt);
            }
        });

        btnfisrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-First-icon.png"))); // NOI18N
        btnfisrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfisrtActionPerformed(evt);
            }
        });

        btnprev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Rewind-icon.png"))); // NOI18N
        btnprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprevActionPerformed(evt);
            }
        });

        btnnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Forward-icon.png"))); // NOI18N
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/EduPoLy/icon/Button-Last-icon.png"))); // NOI18N
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmanv)
                    .addComponent(txthoten)
                    .addComponent(txtmatkhau)
                    .addComponent(txtxacnhanmk)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnthem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnxoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnthemmoi))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdotruongphong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdonhanvien)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(btnfisrt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnprev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnnext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlast)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtxacnhanmk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdotruongphong)
                            .addComponent(rdonhanvien))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnfisrt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnprev, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnnext, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnthem)
                                .addComponent(btnsua)
                                .addComponent(btnxoa)
                                .addComponent(btnthemmoi))))
                    .addComponent(btnlast))
                .addGap(28, 28, 28))
        );

        tabs.addTab("CẬP NHÂT", jPanel1);

        tbldanhsachnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MA NV ", "MAT KHAU ", "HO TEN ", "VAI TRO        "
            }
        ));
        tbldanhsachnhanvien.setRowHeight(22);
        tbldanhsachnhanvien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbldanhsachnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldanhsachnhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldanhsachnhanvien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        tabs.addTab("DANH SÁCH", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbldanhsachnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldanhsachnhanvienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tbldanhsachnhanvien.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tbldanhsachnhanvienMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (isValidate()) {
            this.insert();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        this.delele();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnthemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemmoiActionPerformed
        // TODO add your handling code here:
        this.reset();
    }//GEN-LAST:event_btnthemmoiActionPerformed

    private void btnfisrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfisrtActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btnfisrtActionPerformed

    private void btnprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnprevActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnlastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNVQTJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNVQTJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNVQTJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNVQTJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyNVQTJDialog dialog = new QuanLyNVQTJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfisrt;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprev;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemmoi;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdonhanvien;
    private javax.swing.JRadioButton rdotruongphong;
    private javax.swing.ButtonGroup rdovaitro;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbldanhsachnhanvien;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JPasswordField txtmatkhau;
    private javax.swing.JPasswordField txtxacnhanmk;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        setTitle("QUẢN LÝ NHÂN ");
        this.filltable();
        this.row = -1;
        this.updateStatus();
        
        
    }
    NhanVienDAO nvdao = new NhanVienDAO();//lam vc vs bang nhan vien 
    int row = -1;//hang duoc chon hien tai tren bang

    boolean isValidate() {
        if (txtmanv.getText().length() == 0) {
            MsgBOX.alert(this, "MA KHONG DUOC DE TRONG!!!");
            txtmanv.requestFocus();
            return false;
        }
        try{
        String manv = txtmanv.getText();
        if (nvdao.selectByID(manv) != null) {
            throw new Exception();
        }
        }catch(Exception e){
            MsgBOX.alert(this,"MA DA TON TAI!!!");
            txtmanv.requestFocus();
            txtmanv.setText("");
            return false;
        }

        if (txtmatkhau.getText().length() == 0) {
            MsgBOX.alert(this, "MAT KHAU KHONG DUOC DE TRONG!!!");
            txtmatkhau.requestFocus();
            return false;
        }
        try {
            if (txtmatkhau.getText().equals(txtxacnhanmk.getText()) == false) {
                throw new Exception();
            }
        } catch (Exception e) {
            MsgBOX.alert(this, "2 MAT KHAU KHONG KHOP NHAU!!!");
            txtxacnhanmk.requestFocus();
            txtxacnhanmk.setText("");
            return false;
        }
        if (txthoten.getText().length() == 0) {
            MsgBOX.alert(this, "HOTEN KHONG DUOC DE TRONG!!!");
            txthoten.requestFocus();
            return false;
        }
        return true;
    }

    void insert() {
        if (!AUTH.isManager()) {
            MsgBOX.alert(this, "BAN KHONG CO QUYEN THEM!!!");
        } else {
        NhanVien nv = getform();
        String mk2 = new String(txtxacnhanmk.getPassword());
        if (!mk2.equals(nv.getMatKhau())) {
            MsgBOX.alert(this, "XAC NHAN MAT KHAU KHONG DUNG!!!");

        } else {
            try {
                nvdao.insert(nv);
                this.filltable();
                this.reset();
                MsgBOX.alert(this, "THEM MOI THANH CONG!!!");
            } catch (Exception e) {
                MsgBOX.alert(this, "THEM MOI THAT BAI!!!");
            }
        }
        }
    }

    void update() {
        NhanVien nv = getform();
        String mk2 = new String(txtxacnhanmk.getPassword());
        if (!mk2.equals(nv.getMatKhau())) {
            MsgBOX.alert(this, "XAC NHAN MAT KHAU KHONG DUNG!!!");

        } else {
            try {
                nvdao.update(nv);
                this.filltable();
                MsgBOX.alert(this, "SUA THANH CONG!!!");
            } catch (Exception e) {
                MsgBOX.alert(this, "SUA THAT BAI!!!");
            }
        }
    }

    void delele() {
        if (!AUTH.isManager()) {
            MsgBOX.alert(this, "BAN KHONG CO QUYEN XOA NHAN VIEN!!!");
        } else {
            String manv = txtmanv.getText();
            if (manv.equals(AUTH.user.getMaNV())) {
                MsgBOX.alert(this, "BAN KHONG DUOC XOA CHINH BAN!!!");
            } else if (MsgBOX.confirm(this, "BAN CO THUC SU MUON XOA NHAN VIEN NAY?")) {
                try {
                    nvdao.delete(manv);
                    this.filltable();
                    this.reset();
                    MsgBOX.alert(this, "XOA THANH CONG!!!");
                } catch (Exception e) {
                    MsgBOX.alert(this, "XOA THAT BAI!!!");
                }
            }
        }
    }

    void reset() {
        NhanVien nv = new NhanVien();
        this.setForm(nv);
        this.row = -1;
        this.updateStatus();
    }

    void edit() {//double click vao 1 hang 
        String manv = (String) tbldanhsachnhanvien.getValueAt(this.row, 0);
        NhanVien nv = nvdao.selectByID(manv);
        this.setForm(nv);
        tabs.setSelectedIndex(0);
        this.updateStatus();
    }

    void first() {
        this.row = 0;
        this.edit();
    }

    void prev() {//kiem tra da o dau hay chua .neu chua thi dc tro ve
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void next() {//neu dang o cuoi thi k dc next .neu chua den cuoi thi dc next
        if (this.row < tbldanhsachnhanvien.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    void last() {
        this.row = tbldanhsachnhanvien.getRowCount() - 1;
        this.edit();
    }
    DefaultTableModel model;

    void filltable() {//do du lieu vao tblhocvien
        model = (DefaultTableModel) tbldanhsachnhanvien.getModel();//mo hinh du lieu cua bang
        model.setRowCount(0);
        try {
            List<NhanVien> list = nvdao.selectAll();//Doc du lieu tu csdl
            for (NhanVien nv : list) {
                model.addRow(new Object[]{nv.getMaNV(),nv.getMatKhau(), nv.getHoTen(), 
                    nv.getVaiTro() ? "Truong Phong" : "Nhan Vien"});
            }
        } catch (Exception e) {
            MsgBOX.alert(this, "LOI TRUY VAN DU LIEU!!!");
        }
    }

    void setForm(NhanVien nv) {//lấy thông tin của 1 nhân viên có sẵn hiện lên trên form
        txtmanv.setText(nv.getMaNV());
        txtmatkhau.setText(nv.getMatKhau());
        txtxacnhanmk.setText(nv.getMatKhau());
        txthoten.setText(nv.getHoTen());
        rdotruongphong.setSelected(nv.getVaiTro());
        rdonhanvien.setSelected(!nv.getVaiTro());
    }

    NhanVien getform() {//lấy 1 nhân viên từ thông tin nhập trên form .Sau khi gọi hàm này ra thì sẽ nhận đc 1 nhân viên 
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtmanv.getText());
        nv.setMatKhau(new String(txtmatkhau.getPassword()));
        nv.setHoTen(txthoten.getText());
        nv.setVaiTro(rdotruongphong.isSelected());
        return nv;
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean fisrt = (this.row == 0);
        boolean last = (this.row == tbldanhsachnhanvien.getRowCount() - 1);
        //trang thai form
        txtmanv.setEditable(!edit);//khong duoc cap nhap ma.Khi nao gia tri edit=false thi moi dc cap nhap va nguoc lai
        btnthem.setEnabled(!edit);//khi hien thong tin tren o nhap thi khong hien button va nguoc lai
        btnxoa.setEnabled(edit);//khi co thong tin (true) thi hien buuton va nguoc lai
        btnsua.setEnabled(edit);//nhu tren
        //cac thanh dieu huong
        //khi trong trang thai edit thi moi hien button va nguoc lai
        btnfisrt.setEnabled(edit && !fisrt);//chi hien len khi dang edit va khong phai la hang dau tien
        btnprev.setEnabled(edit && !fisrt);//nhu tren
        btnnext.setEnabled(edit && !last);//chi hien len khi dang edit va khong phai la hang cuoi cung
        btnlast.setEnabled(edit && !last);//nhu tren
    }

}
