/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.EduPoLy.UI;

import com.EduPoLy.DAO.ChuyenDeDAO;
import com.EduPoLy.DAO.HocVienDAO;
import com.EduPoLy.DAO.KhoaHocDAO;
import com.EduPoLy.DAO.NguoiHocDAO;
import com.EduPoLy.Entity.ChuyenDe;
import com.EduPoLy.Entity.HocVien;
import com.EduPoLy.Entity.KhoaHoc;
import com.EduPoLy.Entity.NguoiHoc;
import com.EduPoLy.utils.AUTH;
import com.EduPoLy.utils.MsgBOX;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author DUY PHUONG
 */
public class QuanlyHVJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanlyHVJDialog
     */
    public QuanlyHVJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbochuyende = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cbokhoahoc = new javax.swing.JComboBox<>();
        tabs = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldanhsachhocvien = new javax.swing.JTable();
        btnxoahv = new javax.swing.JButton();
        btncapnhatdiem = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldanhsachnguoihoc = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHUYÊN ĐỀ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        cbochuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbochuyendeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbochuyende, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbochuyende, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KHÓA HỌC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 51, 0))); // NOI18N

        cbokhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbokhoahocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbokhoahoc, 0, 281, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbokhoahoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbldanhsachhocvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TT ", "MA HV", "MA NH ", "HO TEN ", "DIEM       "
            }
        ));
        tbldanhsachhocvien.setRowHeight(22);
        jScrollPane2.setViewportView(tbldanhsachhocvien);
        if (tbldanhsachhocvien.getColumnModel().getColumnCount() > 0) {
            tbldanhsachhocvien.getColumnModel().getColumn(0).setResizable(false);
            tbldanhsachhocvien.getColumnModel().getColumn(0).setPreferredWidth(15);
            tbldanhsachhocvien.getColumnModel().getColumn(1).setResizable(false);
            tbldanhsachhocvien.getColumnModel().getColumn(1).setPreferredWidth(15);
            tbldanhsachhocvien.getColumnModel().getColumn(2).setResizable(false);
            tbldanhsachhocvien.getColumnModel().getColumn(2).setPreferredWidth(15);
            tbldanhsachhocvien.getColumnModel().getColumn(3).setPreferredWidth(200);
            tbldanhsachhocvien.getColumnModel().getColumn(4).setResizable(false);
            tbldanhsachhocvien.getColumnModel().getColumn(4).setPreferredWidth(15);
        }

        btnxoahv.setText("XÓA KHỎI KHÓA HỌC");
        btnxoahv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoahvActionPerformed(evt);
            }
        });

        btncapnhatdiem.setText("CẬP NHẬT ĐIỂM");
        btncapnhatdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatdiemActionPerformed(evt);
            }
        });

        btnprint.setText("PRINT EXCEL");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnprint)
                .addGap(28, 28, 28)
                .addComponent(btnxoahv)
                .addGap(27, 27, 27)
                .addComponent(btncapnhatdiem)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoahv)
                    .addComponent(btncapnhatdiem)
                    .addComponent(btnprint))
                .addGap(22, 22, 22))
        );

        tabs.addTab("HỌC VIÊN", jPanel3);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TÌM KIẾM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        txttimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txttimkiemMousePressed(evt);
            }
        });
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttimkiemKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttimkiem)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        tbldanhsachnguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MANH ", "HO TEN", "GIOI TINH ", "NGAY SINH ", "DIEN THOAI ", "EMAIL      "
            }
        ));
        jScrollPane1.setViewportView(tbldanhsachnguoihoc);

        btnthem.setText("THÊM VÀO KHÓA HỌC");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnthem)
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("NGƯỜI HỌC", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxoahvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoahvActionPerformed
        // TODO add your handling code here:
        xoahocvien();
    }//GEN-LAST:event_btnxoahvActionPerformed

    private void btncapnhatdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatdiemActionPerformed
        // TODO add your handling code here:
        updatediem();
    }//GEN-LAST:event_btncapnhatdiemActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        addhocvien();
    }//GEN-LAST:event_btnthemActionPerformed

    private void cbochuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbochuyendeActionPerformed
        // TODO add your handling code here:
        fillcomboboxkhoahoc();
    }//GEN-LAST:event_cbochuyendeActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txttimkiemActionPerformed

    private void txttimkiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttimkiemMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txttimkiemMousePressed

    private void txttimkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyPressed
        // TODO add your handling code here:
        fillnguoihoc();
    }//GEN-LAST:event_txttimkiemKeyPressed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        print();
    }//GEN-LAST:event_btnprintActionPerformed

    private void cbokhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbokhoahocActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbokhoahocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanlyHVJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanlyHVJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanlyHVJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanlyHVJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanlyHVJDialog dialog = new QuanlyHVJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhatdiem;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoahv;
    private javax.swing.JComboBox<String> cbochuyende;
    private javax.swing.JComboBox<String> cbokhoahoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbldanhsachhocvien;
    private javax.swing.JTable tbldanhsachnguoihoc;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        setTitle("QUẢN LÝ HỌC VIÊN");
        this.fillcomboboxchuyende();
    }
    NguoiHocDAO nhdao = new NguoiHocDAO();
    KhoaHocDAO khdao = new KhoaHocDAO();
    ChuyenDeDAO cddao = new ChuyenDeDAO();
    HocVienDAO hvdao = new HocVienDAO();

    //khi chuyên đề thay đổi thì dữ liệu khóa học cũng thay đổi
    void fillcomboboxchuyende() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbochuyende.getModel();
        model.removeAllElements();
        List<ChuyenDe> list = cddao.selectAll();
        for (ChuyenDe cd : list) {
            model.addElement(cd);
        }
        this.fillcomboboxkhoahoc();
    }

    void fillcomboboxkhoahoc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbokhoahoc.getModel();
        model.removeAllElements();
        ChuyenDe chuyende = (ChuyenDe) cbochuyende.getSelectedItem();
        if (chuyende != null) {
            //đưa vào macd vào để lấy danh sách các khóa học liên quan đến CBB 
            List<KhoaHoc> list = khdao.selectbyChuyende(chuyende.getMaCD());
            for (KhoaHoc kh : list) {
                model.addElement(kh);
            }
            //hiển thị các học viên của khóa học đc chọn 
            this.filltablehocvien();
        }

    }
    DefaultTableModel model;

    //lấy các học viên của 1 khóa học đỗ vào bảng
    void filltablehocvien() {
        model = (DefaultTableModel) tbldanhsachhocvien.getModel();
        model.setRowCount(0);
        //khóa học đc chọn trong CBB khoahoc
        KhoaHoc khoahoc = (KhoaHoc) cbokhoahoc.getSelectedItem();
        if (khoahoc != null) {
            //lấy ra danh sách các học viên tương ứng vs khóa học đc chọn 
            List<HocVien> list = hvdao.selectbykhoahoc(khoahoc.getMaKH());
            for (int i = 0; i < list.size(); i++) {//duyệt qua từng hocvien
                //lấy hocvien từ phần tử thứ i ra 
                HocVien hv = list.get(i);
                //từ hocvien lấy ra manh
                //từ manh sau đó nhdao.selectByID để lấy đc người học sau và họ tên
                String hoten = nhdao.selectByID(hv.getMaNH()).getHoTen();
                model.addRow(new Object[]{i + 1, hv.getMaHV(), hv.getMaNH(), hoten, hv.getDiem()});
            }
            //đỗ dữ liệu vào bảng người học
            this.fillnguoihoc();
        }
    }
    List<NguoiHoc> list;

    void fillnguoihoc() {
        DefaultTableModel model = (DefaultTableModel) tbldanhsachnguoihoc.getModel();
        model.setRowCount(0);
        //hiển thị dữ liệu CBBkhoahoc được chọn
        KhoaHoc khoahoc = (KhoaHoc) cbokhoahoc.getSelectedItem();
        String keyword = txttimkiem.getText();
        //lấy ra danh sách người học không nằm trong khóa học (k phải là HOCVIEN) và phải phụ thuộc vào từ khóa tìm kiếm
        list = nhdao.selectNotInCouurse(khoahoc.getMaKH(), keyword);
        for (NguoiHoc nh : list) {
            model.addRow(new Object[]{nh.getMaNH(), nh.getHoTen(), nh.isGioiTinh() ? "Nam" : "Nu",
                nh.getNgaySinh(), nh.getDienThoai(), nh.getEmail()});
        }
    }

    void addhocvien() {
        //lấy dữ liệu từ CBBkhoahoc
        KhoaHoc khoahoc = (KhoaHoc) cbokhoahoc.getSelectedItem();
        //Duyẹt qua từng số nguyên
        //(index) là 1 mảng chứa các hàng dc chọn trên bảng 
        for (int index : tbldanhsachnguoihoc.getSelectedRows()) {//(rows) chon nhieu hang
            //tao 1 hoc vien moi
            HocVien hv = new HocVien();
            hv.setMaKH(khoahoc.getMaKH());
            //từ người học sang học viên thì chưa có điểm
            hv.setDiem(0);
            //lấy manh từ hàng được chọn và cột đầu tiên
            hv.setMaNH((String) tbldanhsachnguoihoc.getValueAt(index, 0));
            hvdao.insert(hv);
        }
        //do va hien thi du lieu vao bang hc vien
        this.filltablehocvien();
        this.tabs.setSelectedIndex(0);
    }

    void xoahocvien() {
        if (!AUTH.isManager()) {
            MsgBOX.alert(this, "BAN KHONG CO QUYEN XOA HOC VIEN!!!");
        } else {
            if (MsgBOX.confirm(this, "BAN CO MUON XOA HOC VIEN NAY KHONG!!!")) {
                //duyệt qua các hàng đc chon trên tblhocvien và xóa khỏi hocvien
                for (int index : tbldanhsachhocvien.getSelectedRows()) {//rows co the xoa nhieu hoc vien(hang)
                    int mahv = (Integer) tbldanhsachhocvien.getValueAt(index, 1);
                    hvdao.delete(mahv);
                }
                //đỗ lại dữ liệu
                this.filltablehocvien();
            }
        }

    }

    void updatediem() {
        //duyệt qua tất cả các hàng trên bảng 
        for (int i = 0; i < tbldanhsachhocvien.getRowCount(); i++) {
            //lấy gía trị tại hàng thứ (i) và cột thứ 2(mahv)
            int mahv = (Integer) tbldanhsachhocvien.getValueAt(i, 1);
            HocVien hv = hvdao.selectByID(mahv);
            //hv.setDiem((Double) tbldanhsachhocvien.getValueAt(i, 4));
            //điểm đc lấy từ giao diện  
            hv.setDiem(Double.parseDouble(tbldanhsachhocvien.getValueAt(i, 4).toString()));
            //cập nhật vào db           
            hvdao.update(hv);
        }
        MsgBOX.alert(this, "CAP NHAT THANH CONG!!!");
    }
    void print() {
        FileOutputStream excelfou = null;
        BufferedOutputStream excelBOU = null;
        XSSFWorkbook exceljtableExporter = null;
        //chon noi luu file 
        JFileChooser excelfile = new JFileChooser("d:\\prinexcel");
        //Thanh tiu de
        excelfile.setDialogTitle("Save As");
        //cac dang ten duoi mo rong cua excel
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlxs", "xlsm");
        excelfile.setFileFilter(fnef);
        int excelchoose = excelfile.showSaveDialog(null);

        //kiểm tra xem nút lưu có được nhấp không
        if (excelchoose == JFileChooser.APPROVE_OPTION) {
            try {
                //import thu vien apache poi excel
                exceljtableExporter = new XSSFWorkbook();
                XSSFSheet excelsheet = exceljtableExporter.createSheet("JTable Sheet");
                // vòng lặp để lấy cột và hàng của bảng
                for (int i = 0; i < model.getRowCount(); i++) {
                    XSSFRow excelrow = excelsheet.createRow(i);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        XSSFCell excelCell = excelrow.createCell(j);
                        excelCell.setCellValue(tbldanhsachhocvien.getValueAt(i, j).toString());
                    }
                }
                //nối phần mở rộng tệp xlsx vào các tệp đã chọn. để tạo tên tệp duy nhất  
                excelfou = new FileOutputStream(excelfile.getSelectedFile() + ".xlsx");
                excelBOU = new BufferedOutputStream(excelfou);
                exceljtableExporter.write(excelBOU);
                MsgBOX.alert(this, "TAO VA THEM FILE EXCEL THANH CONG!!!");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                MsgBOX.alert(this, "THEM THAT BAI!!!");
            } finally {
                try {
                    if (excelBOU != null) {
                        excelBOU.close();
                    }
                    if (excelfou != null) {
                        excelfou.close();
                    }
                    if (exceljtableExporter != null) {
                        exceljtableExporter.close();
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }

        }
    }

}
